In [126]:
from pymongo import MongoClient
myclient = MongoClient('mongodb+srv://sirisak:1234@cluster0-s9y0s.mongodb.net/test?retryWrites=true&w=majority')
import pandas as pd
import numpy as np
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize
db = myclient["test"]
records = db["posts"]
test_col = db["types"]
user_col = db["users"]

In [107]:
data = pd.DataFrame(records.find())
data

,_id,photo,title,body,created,postedBy,__v,updated,likes,bodys,...,tag1,tag2,tag3,tag4,tag5,tag6,followers,following,advertisement,comments
0,5d24f6f4884f593e74d4b399,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Strawberry Yogurt,Milk with strawberry,2019-07-09 20:20:04.604,5d208546d6f6f23ee441c2fd,0,2019-10-16 19:56:06.786,"[5d2f19959b09d20d4cf4320f, 5da722d1effb7d41944...",Very very delicious,...,sweet,0,0,0,0,0,NaN,NaN,NaN,NaN
1,5d2f16258ed63b1dcceb7002,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Pad Thai (Udontani),4 ounces dried Thai rice noodles\n1 ounce tama...,2019-07-17 12:35:49.552,5d2f15848ed63b1dcceb7000,0,2019-07-17 12:46:15.086,"[5d2f1d399b09d20d4cf43216, 5d2f1d399b09d20d4cf...",\n1. Sauté the scallions and garlic.\n2 Cook t...,...,seafood,traditional,0,0,0,0,NaN,NaN,NaN,NaN
2,5d2f191e9b09d20d4cf4320e,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Pancake,"whisk, two mixing bowls, pan or griddle, veget...",2019-07-17 12:48:30.463,5d2f15848ed63b1dcceb7000,0,NaT,"[5d2f19959b09d20d4cf4320f, 5d305984d6ef2d0ecc1...","1. Mix flour, baking powder, salt, and sugar\n...",...,veggie,0,0,0,0,0,NaN,NaN,NaN,NaN
3,5d2f1a009b09d20d4cf43211,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Ramen noodles,2½ cups (590 milliliters) water\n1 packet of r...,2019-07-17 12:52:16.250,5d2f19959b09d20d4cf4320f,1,2019-10-16 18:46:11.369,"[5d305984d6ef2d0ecc15d2be, 5d2f4b729b09d20d4cf...",sss,...,soup,0,0,0,0,0,[],[],{},NaN
4,5d2f1a789b09d20d4cf43213,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",Lasagna (Italy),2 x 28 oz. cans tomatoes - crushed or whole is...,2019-07-17 12:54:16.960,5d2f19959b09d20d4cf4320f,0,2019-07-17 12:59:23.448,"[5d2f1d399b09d20d4cf43216, 5d2f4b729b09d20d4cf...",1. PREHEAT oven to 350°F. Brown meat in large ...,...,veggie,traditional,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,5d5d605c1c9d4400001100f0,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Dark chocolate veggie bite,Dark chocolate combine with vegetable,2019-08-21 15:09:00.767,5d32e1e282cebe4330489703,0,NaT,[5d32e1e282cebe4330489703],NaN,...,veggie,sweet,0,0,0,0,NaN,NaN,NaN,[]
105,5d5d60c51c9d4400001100f1,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Sukiyaki with fresh veggie,Stir fried sukiyaki with fresh vegetable,2019-08-21 15:09:00.767,5d32e1e282cebe4330489703,0,NaT,[],NaN,...,veggie,street,0,0,0,0,NaN,NaN,NaN,[]
106,5d5d61431c9d4400001100f2,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Veggie stick deep fried,Fresh vegetable deep fried,2019-08-21 15:09:00.767,5d32e1e282cebe4330489703,0,NaT,[],NaN,...,veggie,street,0,0,0,0,NaN,NaN,NaN,[]
107,5da73e651312a31c5847b37a,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Chicken burgers,1 pound extra-lean ground chicken\n\n½ cup Ita...,2019-10-16 15:59:33.505,5d2f15848ed63b1dcceb7000,0,NaT,"[5d305984d6ef2d0ecc15d2be, 5d99b17547dd940c7cb...","Step 1\nMix ground chicken, 1/4 cup bread crum...",...,veggie,street,sweet,0,0,0,NaN,NaN,NaN,NaN
108,5da757987a7f2510cc57780d,{'data': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x0...,Vegan burger,Vegan burger,2019-10-16 17:47:04.918,5d2f15848ed63b1dcceb7000,0,NaT,"[5d46f4810fe7493978544fff, 5d99b17547dd940c7cb...",Vegan burger,...,veggie,street,0,0,0,0,NaN,NaN,NaN,NaN

In [74]:
# Auto Tag before by using text clustering

In [75]:
# Label 
veggie = ['vegetable','vegetables','basil','basils','veggie','krapow','salad','salads','muchroom','tomato','tomatoes',
          'leaves','leaf','kimchi','onion','onions','vegan']
soup = ['boil','boiled','soup','stew']
seafood = ['shrimp','scallop','crab','oyster','prawn','salmon','squid','octopus','cutterfish','mussel','fish']
traditional = ['thai','korean','udontani','italy','italian']
street = ['grill','grilled','fry','fried','barbecue','roast','burger','burgers','cheese','egg']
sweet = ['sweet','flour','chocolate','egg','bread','ice','cream','cheese','pie','blueberry','strawberry','tart']
food_tags = ['veggie','soup','seafood','traditional','street','sweet']

In [76]:
stop_food = ['(',')','[',']',',','/','1/2','1','2','3','4','5','6','7','8','9','.','bowl','bowls','mix','mixed','divided','divide','freshly','ground',
            'spoon','spoons','tablespoon','tablespoons','cup','teaspoon','teaspoons','dried','taste','beaten','or','ladle',
            'measuring','spatula','griddle','pan','one','two','three','four','six','seven','eight','nine','ten','mixing','large',
            'to','into','cut','ounces']

In [88]:
bag_of_word = pd.DataFrame(columns=['food','veggie','soup','seafood','traditional','street','sweet'])
bag_of_word

Empty DataFrame
Columns: [food, veggie, soup, seafood, traditional, street, sweet]
Index: []

In [78]:
def stop_words(t):
    text = t.lower()
    stop_words = set(stopwords.words('english'))   
    word_tokens = word_tokenize(text)   
    filtered_sentence = [] 
    for w in word_tokens: 
        if w not in stop_words: 
            if w not in stop_food:
                filtered_sentence.append(w) 
            
    return filtered_sentence

In [79]:
def tokenize(body):
    word_count = {}
    word_count = dict.fromkeys(food_tags, 0)
    stop_word = stop_words(body)
    for i in range(0, len(stop_word)):
        if stop_word[i] in veggie:
            word_count['veggie'] += 1            
        elif stop_word[i] in soup:
            word_count['soup'] += 1
        elif stop_word[i] in seafood:
            word_count['seafood'] += 1
        elif stop_word[i] in traditional:
            word_count['traditional'] += 1
        elif stop_word[i] in street:
            word_count['street'] += 1
        elif stop_word[i] in sweet:
            word_count['sweet'] += 1
    return word_count

In [80]:
def add_title(df):
    bag_of_word['food'] = df['title']
    for i in range(0, len(df)):
        word_count_dict = tokenize(df['body'][i])
        for k,e in word_count_dict.items():
            bag_of_word[k][i] = e

In [89]:
add_title(data)
bag_of_word

                           food veggie soup seafood traditional street sweet
0             Strawberry Yogurt      0    0       0           0      0     1
1           Pad Thai (Udontani)      0    0       2           1      0     0
2                       Pancake      1    0       0           0      0     0
3                 Ramen noodles      0    1       0           0      0     0
4               Lasagna (Italy)      5    0       0           2      0     0
..                          ...    ...  ...     ...         ...    ...   ...
104  Dark chocolate veggie bite      1    0       0           0      0     1
105  Sukiyaki with fresh veggie      1    0       0           0      1     0
106     Veggie stick deep fried      1    0       0           0      1     0
107             Chicken burgers      1    0       0           0      1     1
108                Vegan burger      1    0       0           0      1     0

[109 rows x 7 columns]

In [82]:
#auto tag

In [96]:
auto_tag = pd.DataFrame(columns=['_id_post','food','1','2','3','4','5','6'])
auto_tag['food'] = bag_of_word['food']
auto_tag['_id_post'] = data['_id']
auto_tag = auto_tag.fillna('0')
auto_tag

                     _id_post                        food  1  2  3  4  5  6
0    5d24f6f4884f593e74d4b399           Strawberry Yogurt  0  0  0  0  0  0
1    5d2f16258ed63b1dcceb7002         Pad Thai (Udontani)  0  0  0  0  0  0
2    5d2f191e9b09d20d4cf4320e                     Pancake  0  0  0  0  0  0
3    5d2f1a009b09d20d4cf43211               Ramen noodles  0  0  0  0  0  0
4    5d2f1a789b09d20d4cf43213             Lasagna (Italy)  0  0  0  0  0  0
..                        ...                         ... .. .. .. .. .. ..
104  5d5d605c1c9d4400001100f0  Dark chocolate veggie bite  0  0  0  0  0  0
105  5d5d60c51c9d4400001100f1  Sukiyaki with fresh veggie  0  0  0  0  0  0
106  5d5d61431c9d4400001100f2     Veggie stick deep fried  0  0  0  0  0  0
107  5da73e651312a31c5847b37a             Chicken burgers  0  0  0  0  0  0
108  5da757987a7f2510cc57780d                Vegan burger  0  0  0  0  0  0

[109 rows x 8 columns]

In [97]:
def set_tag(tag_table, info):
    for i in range(0,len(tag_table)):
        if tag_table['food'][i] == info['food'][i]:
            for tag in range(0,len(food_tags)):
                if str(info[food_tags[tag]][i]) != '0':
                    for tag_slot in range(0,len(food_tags)):
                        if str(tag_table[str(tag_slot+1)][i]) == '0':
                            tag_table[str(tag_slot+1)][i] = food_tags[tag]
                            break

In [98]:
set_tag(auto_tag, bag_of_word)
auto_tag

,_id_post,food,1,2,3,4,5,6
0,5d24f6f4884f593e74d4b399,Strawberry Yogurt,sweet,0,0,0,0,0
1,5d2f16258ed63b1dcceb7002,Pad Thai (Udontani),seafood,traditional,0,0,0,0
2,5d2f191e9b09d20d4cf4320e,Pancake,veggie,0,0,0,0,0
3,5d2f1a009b09d20d4cf43211,Ramen noodles,soup,0,0,0,0,0
4,5d2f1a789b09d20d4cf43213,Lasagna (Italy),veggie,traditional,0,0,0,0
...,...,...,...,...,...,...,...,...
104,5d5d605c1c9d4400001100f0,Dark chocolate veggie bite,veggie,sweet,0,0,0,0
105,5d5d60c51c9d4400001100f1,Sukiyaki with fresh veggie,veggie,street,0,0,0,0
106,5d5d61431c9d4400001100f2,Veggie stick deep fried,veggie,street,0,0,0,0
107,5da73e651312a31c5847b37a,Chicken burgers,veggie,street,sweet,0,0,0
108,5da757987a7f2510cc57780d,Vegan burger,veggie,street,0,0,0,0

In [99]:
dict_auto_tag = auto_tag.to_dict(orient='records')

In [100]:
test_col.insert_many(dict_auto_tag)

In [101]:
test = auto_tag[['_id_post','1','2','3','4','5','6']]
test

                     _id_post        1            2      3  4  5  6
0    5d24f6f4884f593e74d4b399    sweet            0      0  0  0  0
1    5d2f16258ed63b1dcceb7002  seafood  traditional      0  0  0  0
2    5d2f191e9b09d20d4cf4320e   veggie            0      0  0  0  0
3    5d2f1a009b09d20d4cf43211     soup            0      0  0  0  0
4    5d2f1a789b09d20d4cf43213   veggie  traditional      0  0  0  0
..                        ...      ...          ...    ... .. .. ..
104  5d5d605c1c9d4400001100f0   veggie        sweet      0  0  0  0
105  5d5d60c51c9d4400001100f1   veggie       street      0  0  0  0
106  5d5d61431c9d4400001100f2   veggie       street      0  0  0  0
107  5da73e651312a31c5847b37a   veggie       street  sweet  0  0  0
108  5da757987a7f2510cc57780d   veggie       street      0  0  0  0

[109 rows x 7 columns]

In [102]:
def update_db(df):
    for i in range(0, len(df)):
        key = { '_id': df['_id_post'][i]}
        new_data = {
            '$set': {
                'tag1' : str(df['1'][i]),
                'tag2' : str(df['2'][i]),
                'tag3' : str(df['3'][i]),
                'tag4' : str(df['4'][i]),
                'tag5' : str(df['5'][i]),
                'tag6' : str(df['6'][i]),
                    }
        }
        records.update_many (key,new_data)

In [103]:
update_db(test)

In [272]:
# count like
test1 = data

In [273]:
for i in range(0,len(test1)):
    test1['num_like'][i] = len(test1['likes'][i])

C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [274]:
def update_num_like(df):
    for i in range(0,len(df)):
        key = {'_id': df['_id'][i]}
        new_value = {'$set': {
            'num_like': str(df['num_like'][i])
        }}
        records.update_many(key, new_value)
    
update_num_like(test1)

KeyboardInterrupt:

In [104]:
#Personalized

In [275]:
user_data = pd.DataFrame(user_col.find())
user_data

,_id,name,email,salt,hashed_password,created,__v,updated,photo,about,personalization,followers,following,dob,gender,likes,role,history
0,5d208546d6f6f23ee441c2fd,Frong mAaa,frong@gmail.com,5aacf070-a1b0-11e9-9203-39e6c29c029e,2395ab4816d72cde936bb586e2f1684e8061874d,2019-07-06 11:25:58.197,0,2019-07-10 15:01:11.601,"{'contentType': 'image/png', 'data': b'\x89PNG...",My name is Rain.,veggie,[5d2f19959b09d20d4cf4320f],[],NaN,NaN,NaN,NaN,NaN
1,5d2f15848ed63b1dcceb7000,Lisa,lisa@gmail.com,08792ea0-a88f-11e9-99e9-dd340017b15c,98367dbbb7ed77c35b352be6c29c36fbbfb6424b,2019-07-17 12:33:08.746,0,2019-07-29 14:15:07.172,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",Oh my god! Oh my god daddy!,streetfood,[5d2f19959b09d20d4cf4320f],NaN,2011-07-15,female,NaN,NaN,NaN
2,5d2f19959b09d20d4cf4320f,Rosé,rose@gmail.com,74cce4a0-a891-11e9-b002-e7cd9f10410d,e7f4b48738aea80316d5db45162868fcfde5335c,2019-07-17 12:50:29.482,3,2019-10-15 13:21:27.033,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",Best when it's the four of us ma boy \t— Park ...,Veggie,[],"[5d319cc13f5b8b0fc4038e07, 5d319cc13f5b8b0fc40...",2019-07-05,male,"[5d3f1c8920f12936c0b6b45b, 5d3f1afd20f12936c0b...",subscriber,[]
3,5d2f1d399b09d20d4cf43216,Jennie,jennie@gmail.com,a018f5c0-a893-11e9-b002-e7cd9f10410d,f6e741ad35c11d7a23848f6653ada88e7f01820f,2019-07-17 13:06:01.116,1,2019-10-07 11:50:47.705,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,veggie,[],[],2019-07-04,female,"[5d3f1afd20f12936c0b6b459, 5d3f1c8920f12936c0b...",subscriber,NaN
4,5d2f1e299b09d20d4cf43219,jisoo,jisoo@gmail.com,2f53ad70-a894-11e9-b002-e7cd9f10410d,d085bb731fbe20d3d6b0bd45bd56343a54a502bb,2019-07-17 13:10:01.415,0,2019-07-17 13:10:14.832,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,veggie,[5d2f19959b09d20d4cf4320f],NaN,2019-07-19,female,NaN,NaN,NaN
5,5d2f4b729b09d20d4cf4321c,Ronaldo,ronaldo@gmail.com,2d8031b0-a8af-11e9-b002-e7cd9f10410d,3578e69d58c027e20a940d85149fb79a7be48742,2019-07-17 16:23:14.764,0,2019-07-17 16:24:17.678,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,Veggie,NaN,NaN,2019-07-01,male,NaN,NaN,NaN
6,5d305984d6ef2d0ecc15d2be,mase,mase@gmail.com,26b0a760-a950-11e9-bd76-5732f75050e1,d9603b9d1e6de0974f8742a93ef3a3d4f94b7ef3,2019-07-18 11:35:32.310,1,2019-08-21 14:38:39.316,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,streetfood,[],[],2019-07-05,female,NaN,subscriber,NaN
7,5d319a3a3f5b8b0fc4038e03,Kittinut Saengsri,zmack_tem@hotmail.com,4f7b9000-aa0f-11e9-920d-354d1a26d57e,24aa7893dd6924e9c40cac0139c4d23057ee6729,2019-07-19 10:23:54.624,1,2019-08-18 11:47:35.576,"{'contentType': 'image/gif', 'data': b'GIF89a}...",NaN,Veggie,[],[],1997-09-19,male,NaN,subscriber,NaN
8,5d32e1e282cebe4330489703,Kao,supassara@gmail.com,9bae5b60-aad2-11e9-893c-b71d0512508d,e57ffe39d8cb448a891f00acecb696deccade294,2019-07-20 09:41:54.326,1,2019-08-21 14:58:26.371,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,streetfood,[],[],2019-07-12,other,NaN,subscriber,NaN
9,5d46f4810fe7493978544fff,Apple,apple@gmail.com,77537270-b6c9-11e9-a264-7defdded8060,ae435de5c2405b98afa36dc6c6d0482ea79dccd9,2019-08-04 15:06:41.816,1,2019-08-21 14:41:07.840,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,healthyfood,[],[],2019-08-03,female,NaN,subscriber,NaN
10,5d99b17547dd940c7cbc3984,Bill,bill@gmail.com,4c08a720-e81a-11e9-a88e-9bf37b2cd08e,f08caea60f3ce144e2441d33a8ba5f4671614230,2019-10-06 09:18:45.394,0,NaT,NaN,NaN,veggie,[],[],2019-10-03,male,NaN,subscriber,[]
11,5d99b8deaeb85224a8b0df63,Master,master@gmail.com,b6b0be10-e81e-11e9-9741-c1235fd76a79,ad76f2a6c583aa914903b624bf695c047e1e5c85,2019-10-06 09:50:22.321,0,2019-10-16 16:36:47.732,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,NaN,[],[],2019-10-05,male,NaN,admin,NaN
12,5d99f7e8dc74ea38a429e2e2,testper,testper@gmail.com,49f16dd0-e844-11e9-86fe-ed64962c5095,ad905f348453bf2bb68c4ad2ffad1b7653ac8063,2019-10-06 14:19:20.749,0,NaT,NaN,NaN,veggie,[],[],01-02-1998,male,NaN,subscriber,NaN
13,5d9a198c354ba80704674eec,testper,testperr@gmail.com,572920b0-e858-11e9-976a-0d2e1f6ed857,82ddaec149cdddc7491cd25b497430564d208c7e,2019-10-06 16:42:52.859,0,NaT,NaN,NaN,Streetfood,[],[],2019-10-04,male,NaN,subscriber,NaN
14,5d9c795e8e9b912a1c6f7486,Testhis,testhis@gmail.com,a116e430-e9c2-11e9-94e7-1f0d73d79501,c6125f7832b761d6508ad8c525e0cae55598867c,2019-10-08 11:56:14.707,0,NaT,NaN,NaN,veggie,[],[],01-02-1998,male,NaN,subscriber,[]
15,5da722d1effb7d41944f42bd,Bam,bam@gmail.com,81afa300-f01d-11e9-836f-639278108ac0,71c9d3a92275379c3a69169746dd9be39b773e26,2019-10-16 14:01:53.200,0,2019-10-16 14:02:12.852,"{'contentType': 'image/jpeg', 'data': b'\xff\x...",NaN,Streetfood,[],[],2019-10-03,female,NaN,subscriber,NaN

In [282]:
food_rate = pd.DataFrame(columns=['_id_post','food','1','2','3','4','5','6','veggie_c','soup_c','seafood_c','traditional_c','street_c','sweet_c'])

In [283]:
utest = pd.DataFrame(columns=['_id','veggie_rate','soup_rate','seafood_rate','traditional_rate','street_rate','sweet_rate','likes','post_like'])

In [284]:
utest['_id'] = user_data['_id']
for i in range(0,len(users_with_post)):
    utest['likes'][i] = list()
utest

,_id,veggie_rate,soup_rate,seafood_rate,traditional_rate,street_rate,sweet_rate,likes,post_like
0,5d208546d6f6f23ee441c2fd,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
1,5d2f15848ed63b1dcceb7000,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
2,5d2f19959b09d20d4cf4320f,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
3,5d2f1d399b09d20d4cf43216,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
4,5d2f1e299b09d20d4cf43219,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
5,5d2f4b729b09d20d4cf4321c,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
6,5d305984d6ef2d0ecc15d2be,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
7,5d319a3a3f5b8b0fc4038e03,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
8,5d32e1e282cebe4330489703,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
9,5d46f4810fe7493978544fff,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
10,5d99b17547dd940c7cbc3984,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
11,5d99b8deaeb85224a8b0df63,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
12,5d99f7e8dc74ea38a429e2e2,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
13,5d9a198c354ba80704674eec,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
14,5d9c795e8e9b912a1c6f7486,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN
15,5da722d1effb7d41944f42bd,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN

In [285]:
def get_post_to_user(users, df):
    for i in range(0,len(df['likes'])):
        for e in range(0,len(df['likes'][i])):
            for u in range(0,len(users['_id'])):
                if df['likes'][i][e] == users['_id'][u]:
                    users['likes'][u].append(df['_id'][i])

get_post_to_user(utest,data)
for i in range(0,len(utest)):
    utest['post_like'][i] = len(utest['likes'][i])
utest

,_id,veggie_rate,soup_rate,seafood_rate,traditional_rate,street_rate,sweet_rate,likes,post_like
0,5d208546d6f6f23ee441c2fd,NaN,NaN,NaN,NaN,NaN,NaN,[],0
1,5d2f15848ed63b1dcceb7000,NaN,NaN,NaN,NaN,NaN,NaN,"[5d2f16258ed63b1dcceb7002, 5d5d2edc1c9d4400001...",2
2,5d2f19959b09d20d4cf4320f,NaN,NaN,NaN,NaN,NaN,NaN,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",16
3,5d2f1d399b09d20d4cf43216,NaN,NaN,NaN,NaN,NaN,NaN,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",17
4,5d2f1e299b09d20d4cf43219,NaN,NaN,NaN,NaN,NaN,NaN,[],0
5,5d2f4b729b09d20d4cf4321c,NaN,NaN,NaN,NaN,NaN,NaN,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",22
6,5d305984d6ef2d0ecc15d2be,NaN,NaN,NaN,NaN,NaN,NaN,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",21
7,5d319a3a3f5b8b0fc4038e03,NaN,NaN,NaN,NaN,NaN,NaN,"[5d2f16258ed63b1dcceb7002, 5d2f1a009b09d20d4cf...",32
8,5d32e1e282cebe4330489703,NaN,NaN,NaN,NaN,NaN,NaN,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21
9,5d46f4810fe7493978544fff,NaN,NaN,NaN,NaN,NaN,NaN,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21
10,5d99b17547dd940c7cbc3984,NaN,NaN,NaN,NaN,NaN,NaN,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",22
11,5d99b8deaeb85224a8b0df63,NaN,NaN,NaN,NaN,NaN,NaN,[5d5d47ec1c9d4400001100b3],1
12,5d99f7e8dc74ea38a429e2e2,NaN,NaN,NaN,NaN,NaN,NaN,[5d2f16258ed63b1dcceb7002],1
13,5d9a198c354ba80704674eec,NaN,NaN,NaN,NaN,NaN,NaN,[],0
14,5d9c795e8e9b912a1c6f7486,NaN,NaN,NaN,NaN,NaN,NaN,[],0
15,5da722d1effb7d41944f42bd,NaN,NaN,NaN,NaN,NaN,NaN,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",15

In [286]:
food_rate['_id_post'] = auto_tag['_id_post']
food_rate['food'] = auto_tag['food']
food_rate['1'] = auto_tag['1']
food_rate['2'] = auto_tag['2']
food_rate['3'] = auto_tag['3']
food_rate['4'] = auto_tag['4']
food_rate['5'] = auto_tag['5']
food_rate['6'] = auto_tag['6']
food_rate = food_rate.fillna("0")
food_tags_constant = ['veggie_c','soup_c','seafood_c','traditional_c','street_c','sweet_c']
food_rate

,_id_post,food,1,2,3,4,5,6,veggie_c,soup_c,seafood_c,traditional_c,street_c,sweet_c
0,5d24f6f4884f593e74d4b399,Strawberry Yogurt,sweet,0,0,0,0,0,0,0,0,0,0,0
1,5d2f16258ed63b1dcceb7002,Pad Thai (Udontani),seafood,traditional,0,0,0,0,0,0,0,0,0,0
2,5d2f191e9b09d20d4cf4320e,Pancake,veggie,0,0,0,0,0,0,0,0,0,0,0
3,5d2f1a009b09d20d4cf43211,Ramen noodles,soup,0,0,0,0,0,0,0,0,0,0,0
4,5d2f1a789b09d20d4cf43213,Lasagna (Italy),veggie,traditional,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,5d5d605c1c9d4400001100f0,Dark chocolate veggie bite,veggie,sweet,0,0,0,0,0,0,0,0,0,0
105,5d5d60c51c9d4400001100f1,Sukiyaki with fresh veggie,veggie,street,0,0,0,0,0,0,0,0,0,0
106,5d5d61431c9d4400001100f2,Veggie stick deep fried,veggie,street,0,0,0,0,0,0,0,0,0,0
107,5da73e651312a31c5847b37a,Chicken burgers,veggie,street,sweet,0,0,0,0,0,0,0,0,0
108,5da757987a7f2510cc57780d,Vegan burger,veggie,street,0,0,0,0,0,0,0,0,0,0

In [287]:
def set_const(df):
    for idf in range(0, len(df)):
        for ifood in range(0,len(food_tags)):
            if df['1'][idf] == food_tags[ifood]:
                df[food_tags_constant[ifood]][idf] = str(int(df[food_tags_constant[ifood]][idf])+(6/6))
            elif df['2'][idf] == food_tags[ifood]:
                df[food_tags_constant[ifood]][idf] = str(int(df[food_tags_constant[ifood]][idf])+(5/6))
            elif df['3'][idf] == food_tags[ifood]:
                df[food_tags_constant[ifood]][idf] = str(int(df[food_tags_constant[ifood]][idf])+(4/6))
            elif df['4'][idf] == food_tags[ifood]:
                df[food_tags_constant[ifood]][idf] = str(int(df[food_tags_constant[ifood]][idf])+(3/6))
            elif df['5'][idf] == food_tags[ifood]:
                df[food_tags_constant[ifood]][idf] = str(int(df[food_tags_constant[ifood]][idf])+(2/6))
            elif df['6'][idf] == food_tags[ifood]:
                df[food_tags_constant[ifood]][idf] = str(int(df[food_tags_constant[ifood]][idf])+(1/6))

In [288]:
set_const(food_rate)
food_rate

,_id_post,food,1,2,3,4,5,6,veggie_c,soup_c,seafood_c,traditional_c,street_c,sweet_c
0,5d24f6f4884f593e74d4b399,Strawberry Yogurt,sweet,0,0,0,0,0,0,0,0,0,0,1.0
1,5d2f16258ed63b1dcceb7002,Pad Thai (Udontani),seafood,traditional,0,0,0,0,0,0,1.0,0.8333333333333334,0,0
2,5d2f191e9b09d20d4cf4320e,Pancake,veggie,0,0,0,0,0,1.0,0,0,0,0,0
3,5d2f1a009b09d20d4cf43211,Ramen noodles,soup,0,0,0,0,0,0,1.0,0,0,0,0
4,5d2f1a789b09d20d4cf43213,Lasagna (Italy),veggie,traditional,0,0,0,0,1.0,0,0,0.8333333333333334,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,5d5d605c1c9d4400001100f0,Dark chocolate veggie bite,veggie,sweet,0,0,0,0,1.0,0,0,0,0,0.8333333333333334
105,5d5d60c51c9d4400001100f1,Sukiyaki with fresh veggie,veggie,street,0,0,0,0,1.0,0,0,0,0.8333333333333334,0
106,5d5d61431c9d4400001100f2,Veggie stick deep fried,veggie,street,0,0,0,0,1.0,0,0,0,0.8333333333333334,0
107,5da73e651312a31c5847b37a,Chicken burgers,veggie,street,sweet,0,0,0,1.0,0,0,0,0.8333333333333334,0.6666666666666666
108,5da757987a7f2510cc57780d,Vegan burger,veggie,street,0,0,0,0,1.0,0,0,0,0.8333333333333334,0

In [289]:
food_tags_rate = ['veggie_rate','soup_rate','seafood_rate','traditional_rate','street_rate','sweet_rate']
food_tags_constant = ['veggie_c','soup_c','seafood_c','traditional_c','street_c','sweet_c']
utest = utest.fillna("0")
utest

,_id,veggie_rate,soup_rate,seafood_rate,traditional_rate,street_rate,sweet_rate,likes,post_like
0,5d208546d6f6f23ee441c2fd,0,0,0,0,0,0,[],0
1,5d2f15848ed63b1dcceb7000,0,0,0,0,0,0,"[5d2f16258ed63b1dcceb7002, 5d5d2edc1c9d4400001...",2
2,5d2f19959b09d20d4cf4320f,0,0,0,0,0,0,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",16
3,5d2f1d399b09d20d4cf43216,0,0,0,0,0,0,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",17
4,5d2f1e299b09d20d4cf43219,0,0,0,0,0,0,[],0
5,5d2f4b729b09d20d4cf4321c,0,0,0,0,0,0,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",22
6,5d305984d6ef2d0ecc15d2be,0,0,0,0,0,0,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",21
7,5d319a3a3f5b8b0fc4038e03,0,0,0,0,0,0,"[5d2f16258ed63b1dcceb7002, 5d2f1a009b09d20d4cf...",32
8,5d32e1e282cebe4330489703,0,0,0,0,0,0,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21
9,5d46f4810fe7493978544fff,0,0,0,0,0,0,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21
10,5d99b17547dd940c7cbc3984,0,0,0,0,0,0,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",22
11,5d99b8deaeb85224a8b0df63,0,0,0,0,0,0,[5d5d47ec1c9d4400001100b3],1
12,5d99f7e8dc74ea38a429e2e2,0,0,0,0,0,0,[5d2f16258ed63b1dcceb7002],1
13,5d9a198c354ba80704674eec,0,0,0,0,0,0,[],0
14,5d9c795e8e9b912a1c6f7486,0,0,0,0,0,0,[],0
15,5da722d1effb7d41944f42bd,0,0,0,0,0,0,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",15

In [290]:
def add_rate_to_user(user_df, food_df):
    for i_userdf in range(0, len(user_df)):
        if int(user_df['post_like'][i_userdf]) != 0:
            for i_like_userdf in range(0, len(user_df['likes'][i_userdf])):
                for ifooddf in range(0, len(food_df)):
                    if user_df['likes'][i_userdf][i_like_userdf] == food_df['_id_post'][ifooddf]:
                        user_df['veggie_rate'][i_userdf] = str((float(user_df['veggie_rate'][i_userdf]) 
                                                               + float(food_df['veggie_c'][ifooddf]))
                                                              / float(user_df['post_like'][i_userdf]))
                        user_df['soup_rate'][i_userdf] = str((float(user_df['soup_rate'][i_userdf]) 
                                                               + float(food_df['soup_c'][ifooddf]))
                                                              / float(user_df['post_like'][i_userdf]))
                        user_df['seafood_rate'][i_userdf] = str((float(user_df['seafood_rate'][i_userdf]) 
                                                               + float(food_df['seafood_c'][ifooddf]))
                                                              / float(user_df['post_like'][i_userdf]))
                        user_df['traditional_rate'][i_userdf] = str((float(user_df['traditional_rate'][i_userdf]) 
                                                               + float(food_df['traditional_c'][ifooddf]))
                                                              / float(user_df['post_like'][i_userdf]))
                        user_df['street_rate'][i_userdf] = str((float(user_df['street_rate'][i_userdf]) 
                                                               + float(food_df['street_c'][ifooddf]))
                                                              / float(user_df['post_like'][i_userdf]))
                        user_df['sweet_rate'][i_userdf] = str((float(user_df['sweet_rate'][i_userdf]) 
                                                               + float(food_df['sweet_c'][ifooddf]))
                                                              / float(user_df['post_like'][i_userdf]))

In [291]:
add_rate_to_user(utest,food_rate)
utest

C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,_id,veggie_rate,soup_rate,seafood_rate,traditional_rate,street_rate,sweet_rate,likes,post_like
0,5d208546d6f6f23ee441c2fd,0,0,0,0,0,0,[],0
1,5d2f15848ed63b1dcceb7000,0.0,0.0,0.25,0.20833333333333334,0.0,0.0,"[5d2f16258ed63b1dcceb7002, 5d5d2edc1c9d4400001...",2
2,5d2f19959b09d20d4cf4320f,0.0002441406250000139,9.5367431640625e-07,9.097176137395913e-13,7.228014483236697e-19,0.06271956761656856,5.421010862427522e-20,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",16
3,5d2f1d399b09d20d4cf43216,0.05882352941228992,0.05268335707985799,1.2721199227491975e-05,4.148807476448602e-13,0.0028835083745579523,1.2088386483023968e-21,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",17
4,5d2f1e299b09d20d4cf43219,0,0,0,0,0,0,[],0
5,5d2f4b729b09d20d4cf4321c,8.13266698030496e-17,7.305696755801583e-21,6.482562091113777e-17,4.268834097794956e-06,0.047618336146696486,0.03795704983721513,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",22
6,5d305984d6ef2d0ecc15d2be,0.04999999997229897,1.2590017895227573e-12,2.991134245557501e-15,2.6439044052922633e-11,0.04157218491404298,0.03325774754346183,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",21
7,5d319a3a3f5b8b0fc4038e03,0.032257080079034495,8.881784197009338e-16,8.271812699619652e-25,1.9611289353287647e-41,0.02685645315874847,0.0006518363952636719,"[5d2f16258ed63b1dcceb7002, 5d2f1a009b09d20d4cf...",32
8,5d32e1e282cebe4330489703,0.0498866213152527,1.1659615572447308e-08,0.0018898901816354517,7.00079574418264e-22,0.0016248378503995091,0.03977252276572005,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21
9,5d46f4810fe7493978544fff,0.05,0.0,5.0073692015551326e-14,6.304284937036088e-26,0.04157238847264225,1.6323461801426227e-07,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21
10,5d99b17547dd940c7cbc3984,0.04761884434123353,3.7650719496093986e-14,1.512034217354258e-23,4.0090485765846713e-10,0.03960431153692437,0.0014558341250080202,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",22
11,5d99b8deaeb85224a8b0df63,0.0,0.0,1.0,0.0,0.0,0.0,[5d5d47ec1c9d4400001100b3],1
12,5d99f7e8dc74ea38a429e2e2,0.0,0.0,1.0,0.8333333333333334,0.0,0.0,[5d2f16258ed63b1dcceb7002],1
13,5d9a198c354ba80704674eec,0,0,0,0,0,0,[],0
14,5d9c795e8e9b912a1c6f7486,0,0,0,0,0,0,[],0
15,5da722d1effb7d41944f42bd,0.07111111111111162,0.00029629668648071937,1.984090577704431e-05,4.567316521042334e-16,1.4451274929860511e-12,2.2836582605211673e-18,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",15

In [307]:
utest['personality'] = " "

In [308]:
def max_value(df):
    maxi = float("0.0")
    text = " "
    for i in range(0, len(df)):
        maxi = float(df['veggie_rate'][i])
        text = 'veggie'
        if float(df['soup_rate'][i]) > maxi:
            maxi = float(df['soup_rate'][i])
            text = 'soup'
        elif float(df['seafood_rate'][i]) > maxi:
            maxi = float(df['seafood_rate'][i])
            text = 'seafood'
        elif float(df['traditional_rate'][i]) > maxi:
            maxi = float(df['traditional_rate'][i])
            text = 'traditional'
        elif float(df['street_rate'][i]) > maxi:
            maxi = float(df['street_rate'][i])
            text = 'street'
        elif float(df['sweet_rate'][i]) > maxi:
            maxi = float(df['sweet_rate'][i])
            text = 'sweet'
        
        df['personality'][i] = text

In [309]:
max_value(utest)
utest

C:\lab\anaconda\envs\sunenv\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,_id,veggie_rate,soup_rate,seafood_rate,traditional_rate,street_rate,sweet_rate,likes,post_like,personality
0,5d208546d6f6f23ee441c2fd,0,0,0,0,0,0,[],0,veggie
1,5d2f15848ed63b1dcceb7000,0.0,0.0,0.25,0.20833333333333334,0.0,0.0,"[5d2f16258ed63b1dcceb7002, 5d5d2edc1c9d4400001...",2,seafood
2,5d2f19959b09d20d4cf4320f,0.0002441406250000139,9.5367431640625e-07,9.097176137395913e-13,7.228014483236697e-19,0.06271956761656856,5.421010862427522e-20,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",16,street
3,5d2f1d399b09d20d4cf43216,0.05882352941228992,0.05268335707985799,1.2721199227491975e-05,4.148807476448602e-13,0.0028835083745579523,1.2088386483023968e-21,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",17,veggie
4,5d2f1e299b09d20d4cf43219,0,0,0,0,0,0,[],0,veggie
5,5d2f4b729b09d20d4cf4321c,8.13266698030496e-17,7.305696755801583e-21,6.482562091113777e-17,4.268834097794956e-06,0.047618336146696486,0.03795704983721513,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",22,traditional
6,5d305984d6ef2d0ecc15d2be,0.04999999997229897,1.2590017895227573e-12,2.991134245557501e-15,2.6439044052922633e-11,0.04157218491404298,0.03325774754346183,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",21,veggie
7,5d319a3a3f5b8b0fc4038e03,0.032257080079034495,8.881784197009338e-16,8.271812699619652e-25,1.9611289353287647e-41,0.02685645315874847,0.0006518363952636719,"[5d2f16258ed63b1dcceb7002, 5d2f1a009b09d20d4cf...",32,veggie
8,5d32e1e282cebe4330489703,0.0498866213152527,1.1659615572447308e-08,0.0018898901816354517,7.00079574418264e-22,0.0016248378503995091,0.03977252276572005,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21,veggie
9,5d46f4810fe7493978544fff,0.05,0.0,5.0073692015551326e-14,6.304284937036088e-26,0.04157238847264225,1.6323461801426227e-07,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",21,veggie
10,5d99b17547dd940c7cbc3984,0.04761884434123353,3.7650719496093986e-14,1.512034217354258e-23,4.0090485765846713e-10,0.03960431153692437,0.0014558341250080202,"[5d2f16258ed63b1dcceb7002, 5d2f191e9b09d20d4cf...",22,veggie
11,5d99b8deaeb85224a8b0df63,0.0,0.0,1.0,0.0,0.0,0.0,[5d5d47ec1c9d4400001100b3],1,seafood
12,5d99f7e8dc74ea38a429e2e2,0.0,0.0,1.0,0.8333333333333334,0.0,0.0,[5d2f16258ed63b1dcceb7002],1,seafood
13,5d9a198c354ba80704674eec,0,0,0,0,0,0,[],0,veggie
14,5d9c795e8e9b912a1c6f7486,0,0,0,0,0,0,[],0,veggie
15,5da722d1effb7d41944f42bd,0.07111111111111162,0.00029629668648071937,1.984090577704431e-05,4.567316521042334e-16,1.4451274929860511e-12,2.2836582605211673e-18,"[5d24f6f4884f593e74d4b399, 5d2f16258ed63b1dcce...",15,veggie

In [319]:
def update_personalize(df):
    for i in range(0,len(df)):
        key = {'_id': df['_id'][i]}
        new_value = {
            '$set': {
                'veggie_rate': str(df['veggie_rate'][i]),
                'soup_rate': str(df['soup_rate'][i]),
                'seafood_rate': str(df['seafood_rate'][i]),
                'traditional_rate': str(df['traditional_rate'][i]),
                'street_rate': str(df['street_rate'][i]),
                'sweet_rate': str(df['sweet_rate'][i]),
                'likes': df['likes'][i],
                'post_like': str(df['post_like'][i]),
                'personality': df['personality'][i]
            }
        }
        user_col.update_many (key, new_value)

In [320]:
update_personalize(utest)

In [323]:
suggest = pd.DataFrame(columns=['_id_user','personality','suggest1','suggest2','suggest3'])
suggest

Empty DataFrame
Columns: [_id_user, personality, suggest1, suggest2, suggest3]
Index: []

In [325]:
suggest['_id_user'] = utest['_id']
suggest['personality'] = utest['personality']
suggest

                    _id_user  personality suggest1 suggest2 suggest3
0   5d208546d6f6f23ee441c2fd       veggie      NaN      NaN      NaN
1   5d2f15848ed63b1dcceb7000      seafood      NaN      NaN      NaN
2   5d2f19959b09d20d4cf4320f       street      NaN      NaN      NaN
3   5d2f1d399b09d20d4cf43216       veggie      NaN      NaN      NaN
4   5d2f1e299b09d20d4cf43219       veggie      NaN      NaN      NaN
5   5d2f4b729b09d20d4cf4321c  traditional      NaN      NaN      NaN
6   5d305984d6ef2d0ecc15d2be       veggie      NaN      NaN      NaN
7   5d319a3a3f5b8b0fc4038e03       veggie      NaN      NaN      NaN
8   5d32e1e282cebe4330489703       veggie      NaN      NaN      NaN
9   5d46f4810fe7493978544fff       veggie      NaN      NaN      NaN
10  5d99b17547dd940c7cbc3984       veggie      NaN      NaN      NaN
11  5d99b8deaeb85224a8b0df63      seafood      NaN      NaN      NaN
12  5d99f7e8dc74ea38a429e2e2      seafood      NaN      NaN      NaN
13  5d9a198c354ba80704674eec       veggie      NaN      NaN      NaN
14  5d9c795e8e9b912a1c6f7486       veggie      NaN      NaN      NaN
15  5da722d1effb7d41944f42bd       veggie      NaN      NaN      NaN

In [334]:
import random

In [333]:
auto_tag

,_id_post,food,1,2,3,4,5,6
0,5d24f6f4884f593e74d4b399,Strawberry Yogurt,sweet,0,0,0,0,0
1,5d2f16258ed63b1dcceb7002,Pad Thai (Udontani),seafood,traditional,0,0,0,0
2,5d2f191e9b09d20d4cf4320e,Pancake,veggie,0,0,0,0,0
3,5d2f1a009b09d20d4cf43211,Ramen noodles,soup,0,0,0,0,0
4,5d2f1a789b09d20d4cf43213,Lasagna (Italy),veggie,traditional,0,0,0,0
...,...,...,...,...,...,...,...,...
104,5d5d605c1c9d4400001100f0,Dark chocolate veggie bite,veggie,sweet,0,0,0,0
105,5d5d60c51c9d4400001100f1,Sukiyaki with fresh veggie,veggie,street,0,0,0,0
106,5d5d61431c9d4400001100f2,Veggie stick deep fried,veggie,street,0,0,0,0
107,5da73e651312a31c5847b37a,Chicken burgers,veggie,street,sweet,0,0,0
108,5da757987a7f2510cc57780d,Vegan burger,veggie,street,0,0,0,0

In [ ]:
def random_suggest(df, food):    
    for i in range(0,len(df)):
        food_list = []
        if food['1'][i] == df['personality'][i]:
            food_list.append(food['_id_post'][i])
        elif i == len(df)
            if food['1'][i] == df['personality'][i]:
            food_list.append(food['_id_post'][i])
            sample = random.sample(food_list, 3)
            for i in range(0, len(sample)):